<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "profile".
 *
 * @property integer $id
 * @property string $name
 * @property string $surname
 * @property string $patronymic
 * @property string $date_bith
 * @property string $image
 * @property string $email
 * @property string $status
 * @property string $position
 * @property integer $user_id
 * @property integer $department_id
 */
class Profile extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'profile';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

            [['user_id'], 'required'],
            [['user_id', 'department_id'], 'integer'],
            [['name', 'surname', 'patronymic', 'image', 'email', 'status', 'chief', 'position'], 'string', 'max' => 255],

            [['name'], 'match', 'pattern' => '#^\+[0-9]{1,2}\s?\([0-9]{3}\)\s?[0-9]+\-[0-9]+\-[0-9]+$#', 'message' => 'Некорректный номер телефона' ],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'surname' => 'Surname',
            'patronymic' => 'Patronymic',
            'date_bith' => 'Date Bith',
            'image' => 'Image',
            'email' => 'Email',
            'status' => 'Status',
            'chief' => 'chief',
            'position' => 'Position',
            'user_id' => 'User ID',
            'department_id' => 'Department ID',
        ];
    }

    public function getDepartment()
    {
        return $this->hasOne(Department::className(), ['id' => 'department_id']);
    }

    public function saveDepartment($department_id)
    {
        $department = Department::findOne($department_id);

        if($department != null)
        {
            $this->link('department', $department);
            return true;
        }

    }

    public function saveImage($filename)
    {
        $this->image = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->image) ? '/uploads/' . $this->image : '/no-image.png';
    }

    private function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
